### ISSUE TITLE
PuppeteerCapture.start never returns completed promise after updating to Chrome v109

### ISSUE THREAD

**Issue by pdille** [alexey-pelykh/puppeteer-capture#12]
Hi there.

First off, thanks for this amazing plugin!

I was using it successfully but today I updated to Chrome 109 (previously was on Chrome 108) and now my scripts are stuck when attempting to capture. It appears that PuppeteerCapture.start remains in a stuck state and never completes the promise. 

Below is a simple script that exhibits this behavior. When in Chrome 109, I see it print out 'network idle' and then never proceeds further.  If I revert back to Chrome 108, it prints out 'network idle', then 'capture started' and shortly thereafter exits the script with my new mp4 file.

I am running Ubuntu 18.04, node v16.19, puppeteer v19.5.2 (was on 19.5.0 when I first noticed it break and updated to 19.5.2 to see if that made a difference, which it did not), and puppeteer-capture 1.1.1.

Happy to test out anything you need. I'm not afraid to get my hands dirty. :)

Thanks!

```
const { capture, launch } = require('puppeteer-capture');

(async () => {
  const browser = await launch({
    dumpio: true,
    executablePath: "/usr/bin/google-chrome"
  });
  const page = await browser.newPage()
  const recorder = await capture(page)
  await page.goto('https://google.com', {
    waitUntil: 'networkidle0',
  })
  console.log('network idle')
  await recorder.start('capture.mp4')
  console.log('capture started')
  await page.waitForTimeout(1000)
  await recorder.stop()
  await recorder.detach()
  await browser.close()
})()
```

**Comment by alexey-pelykh** [comment]
Hi @pdille, thanks for your report. I'll look into this yet I should note that 19.4.x so far is the last supported (as in, "tested with"), so possibly some extra steps to support 19.5.x are needed.

**Comment by pdille** [comment]
Thanks for the quick response!

Good to know. But as I mentioned, I am successfully able to use this plugin with puppeteer 19.5.x if I revert back to Chrome 108.

**Comment by alexey-pelykh** [comment]
Oh, interesting! Thanks for the update, that'll help
